wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.16
    start_time: 1741099675
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      4: 3.10.16
      5: 0.12.21
      8:
      - 5
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: BinaryMNIST
epochs:
  desc: null
  value: 50
loss:
  desc: null
  value: CrossEntropyLoss()
lr:
  desc: null
  value: 5.0e-06
norm:
  desc: null
  value: normalise
ohe_targets:
  desc: null
  value: true
pretrained_epoch:
  desc: null
  value: 800
pretrained_model_path:
  desc: null
  value: /Users/patmccarthy/Documents/thalamocortex/results/25_02_24_feedforward_mnist_gridsearch/0_CTCNet_TC_none/model.pth
save_path:
  desc: null
  value: /Users/patmccarthy/Documents/thalamocortex/data
thal_output_size:
  desc: null
  value: 2
track_loss_step:
  desc: null
  value: 50
